### ISSUE TITLE
Pip install broken since v0.11.1

### ISSUE THREAD

**Issue by phiadaarr** [pyFFTW/pyFFTW#252]
I am using pyFFTW inside a Docker container for testing. Since v0.11.1 the following Dockerfile does not build anymore:
```
FROM debian:testing-slim
RUN apt-get update && apt-get install -y \
    libfftw3-dev \
    python python-pip python-dev python-future python-scipy \
  && pip install pyfftw
```
I get the console output:
> Collecting pyfftw
>   Downloading https://files.pythonhosted.org/packages/fa/7f/e65fe8b9f1b66aab22c8d76c2f03180714a558fcef4a723263fa8f3754f8/pyFFTW-0.11.1.tar.gz (131kB)
> Requirement already satisfied: numpy<2.0,>=1.10 in /usr/lib/python2.7/dist-packages (from pyfftw)
> Building wheels for collected packages: pyfftw
>   Running setup.py bdist_wheel for pyfftw: started
>   Running setup.py bdist_wheel for pyfftw: finished with status 'error'
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GF_vRa/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpEap4Rmpip-wheel- --python-tag cp27:
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.linux-x86_64-2.7
>   creating build/lib.linux-x86_64-2.7/pyfftw
>   copying pyfftw/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw
>   copying pyfftw/config.py -> build/lib.linux-x86_64-2.7/pyfftw
>   copying pyfftw/_version.py -> build/lib.linux-x86_64-2.7/pyfftw
>   creating build/lib.linux-x86_64-2.7/pyfftw/builders
>   copying pyfftw/builders/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
>   copying pyfftw/builders/builders.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
>   copying pyfftw/builders/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
>   creating build/lib.linux-x86_64-2.7/pyfftw/interfaces
>   copying pyfftw/interfaces/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>   copying pyfftw/interfaces/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>   copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>   copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>   copying pyfftw/interfaces/cache.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>   copying pyfftw/interfaces/dask_fft.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>   UPDATING build/lib.linux-x86_64-2.7/pyfftw/_version.py
>   set build/lib.linux-x86_64-2.7/pyfftw/_version.py to '0.11.1'
>   running build_ext
>   Build pyFFTW with support for FFTW with
>   double precision + openMP
>   single precision + openMP
>   long precision + openMP
>   building 'pyfftw.pyfftw' extension
>   error: unknown file type '.pyx' (from 'pyfftw/pyfftw.pyx')
>   
>   ----------------------------------------
>   Failed building wheel for pyfftw
>   Running setup.py clean for pyfftw
> Failed to build pyfftw
> Installing collected packages: pyfftw
>   Running setup.py install for pyfftw: started
>     Running setup.py install for pyfftw: finished with status 'error'
>     Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GF_vRa/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sIXCAN-record/install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-2.7
>     creating build/lib.linux-x86_64-2.7/pyfftw
>     copying pyfftw/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw
>     copying pyfftw/config.py -> build/lib.linux-x86_64-2.7/pyfftw
>     copying pyfftw/_version.py -> build/lib.linux-x86_64-2.7/pyfftw
>     creating build/lib.linux-x86_64-2.7/pyfftw/builders
>     copying pyfftw/builders/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
>     copying pyfftw/builders/builders.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
>     copying pyfftw/builders/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/builders
>     creating build/lib.linux-x86_64-2.7/pyfftw/interfaces
>     copying pyfftw/interfaces/__init__.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>     copying pyfftw/interfaces/_utils.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>     copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>     copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>     copying pyfftw/interfaces/cache.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>     copying pyfftw/interfaces/dask_fft.py -> build/lib.linux-x86_64-2.7/pyfftw/interfaces
>     UPDATING build/lib.linux-x86_64-2.7/pyfftw/_version.py
>     set build/lib.linux-x86_64-2.7/pyfftw/_version.py to '0.11.1'
>     running build_ext
>     Build pyFFTW with support for FFTW with
>     double precision + openMP
>     single precision + openMP
>     long precision + openMP
>     building 'pyfftw.pyfftw' extension
>     error: unknown file type '.pyx' (from 'pyfftw/pyfftw.pyx')
>     
>     ----------------------------------------
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GF_vRa/pyfftw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sIXCAN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-GF_vRa/pyfftw/
>

**Comment by hgomersall** [comment]
Is this a docker issue?

**Comment by grlee77** [comment]
If you `pip install cython` prior to trying pyfftw, does it work? Both Cython and a C compiler are required to build from source. Usually we also provide wheels as PyPI so that compilation is not necessary, but we just uploaded that source file yesterday and have not yet uploaded the wheels for 0.11.1.

**Comment by phara92** [comment]
Yes it is due to the missing cython installation. Is there a reason why you have not uploaded the wheels?

**Comment by grlee77** [comment]
> Is there a reason why you have not uploaded the wheels?

We have been overhauling how the wheels are built to make it easier to do releases. There is an open PR at pyFFTW/pyFFTW-wheels#24 that builds all of the wheels for 0.11.1, but it is currently awaiting review. Once it has been merged, the wheels will be generated and we will upload them to PyPI.

In the meantime, you can use the wheels for 0.11.0 (e.g. `pip install "pyfftw==0.11.0"`). There are no bug fixes to the user-facing code in 0.11.1, it just had a small change to the setup script.py that was needed for building packages on conda-forge.

**Comment by f0k** [comment]
Not 100% sure it is the same problem, but I also got:
```
building 'pyfftw.pyfftw' extension
error: unknown file type '.pyx' (from 'pyfftw/pyfftw.pyx')
```
So I'm attaching to this issue. In my case it wasn't enough to install cython, I also had to add:
```python
from Cython.Distutils import build_ext
```
to the beginning of `setup.py` (after the existing `build_ext` imports, which are thus overwritten). This may have to do with my version of Cython and/or distutils/setuptools, but if it doesn't break anything, it could be useful to add. I'm happy to send a PR.

**Comment by phara92** [comment]
Apparently the maintainers have uploaded the according wheels such that one does not need to install cython anymore in order to pip-install pyfftw. Thanks!

**Comment by paulmueller** [comment]
I think this issue should not be closed, as it will happen again for future releases.

@grlee77 Is the behavior that I described two posts above intended?

**Comment by paulmueller** [comment]
I am not sure whether we are talking about the same thing.

Here is an example:
Assuming you have a new virtualenv with no system site packages:
```
virtualenv --no-site-packages env
source env/bin/activate
```
(This means cython is not available)

Then you can use pip to install, for instance, the [source tarball package of dclab](https://files.pythonhosted.org/packages/ed/38/0eb4597158060b686ecda4da61dc6bd3aed91eec53ede7498cf376c49b0c/dclab-0.8.0.tar.gz), which has [``cython`` in ``setup_requires``](https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/setup.py#L67) to build a cython extension during setup.

```
pip install https://files.pythonhosted.org/packages/ed/38/0eb4597158060b686ecda4da61dc6bd3aed91eec53ede7498cf376c49b0c/dclab-0.8.0.tar.gz
```

The output will be:
```
Collecting https://files.pythonhosted.org/packages/ed/38/0eb4597158060b686ecda4da61dc6bd3aed91eec53ede7498cf376c49b0c/dclab-0.8.0.tar.gz
  Downloading https://files.pythonhosted.org/packages/ed/38/0eb4597158060b686ecda4da61dc6bd3aed91eec53ede7498cf376c49b0c/dclab-0.8.0.tar.gz (914kB)
    100% |████████████████████████████████| 921kB 748kB/s 
Collecting fcswrite>=0.4.1 (from dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/44/01/267788195016f21cfb3761a0c49f9b3dde1ba7c3c1c0bee3631b1a19c71d/fcswrite-0.4.1-py2.py3-none-any.whl
Collecting h5py>=2.8.0 (from dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/33/0c/1c5dfa85e05052aa5f50969d87c67a2128dc39a6f8ce459a503717e56bd0/h5py-2.8.0-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
    100% |████████████████████████████████| 2.7MB 1.3MB/s 
Collecting imageio>=2.3.0 (from dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/28/b4/cbb592964dfd71a9de6a5b08f882fd334fb99ae09ddc82081dbb2f718c81/imageio-2.4.1.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 2.6MB/s 
Collecting nptdms (from dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/0e/fe/1825c5f203f8d620e03ce5c8f11d68a7e5a9750598687416a0456e3c9843/npTDMS-0.13.0-py2.py3-none-any.whl
Collecting numpy>=1.9.0 (from dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/de/37/fe7db552f4507f379d81dcb78e58e05030a8941757b1f664517d581b5553/numpy-1.15.4-cp27-cp27mu-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.8MB 2.2MB/s 
Collecting pathlib (from dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 3.2MB/s 
Collecting scipy>=0.12.0 (from dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/2a/f3/de9c1bd16311982711209edaa8c6caa962db30ebb6a8cc6f1dcd2d3ef616/scipy-1.1.0-cp27-cp27mu-manylinux1_x86_64.whl (30.8MB)
    100% |████████████████████████████████| 30.8MB 921kB/s 
Collecting statsmodels>=0.5.0 (from dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/ed/56/a1d32debdaba5cc7986aeeeb79e33d74ae3394eabfd008b0113368b91981/statsmodels-0.9.0-cp27-cp27mu-manylinux1_x86_64.whl (7.4MB)
    100% |████████████████████████████████| 7.4MB 1.9MB/s 
Collecting pandas>=0.14 (from dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/b7/e3/f52d484244105fa3d558ce8217a5190cd3d40536076bef66d92d01566325/pandas-0.23.4-cp27-cp27mu-manylinux1_x86_64.whl (8.9MB)
    100% |████████████████████████████████| 8.9MB 2.2MB/s 
Collecting patsy>=0.3.0 (from dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/ea/0c/5f61f1a3d4385d6bf83b83ea495068857ff8dfb89e74824c6e9eb63286d8/patsy-0.5.1-py2.py3-none-any.whl (231kB)
    100% |████████████████████████████████| 235kB 2.3MB/s 
Collecting six (from h5py>=2.8.0->dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pillow (from imageio>=2.3.0->dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/9a/f6/3b3c82c5c75cae471e02fb584136168d732e17ae9db2d21c5dc82f9790f8/Pillow-5.3.0-cp27-cp27mu-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 2.2MB/s 
Collecting enum34 (from imageio>=2.3.0->dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting futures (from imageio>=2.3.0->dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting pytz>=2011k (from pandas>=0.14->dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/f8/0e/2365ddc010afb3d79147f1dd544e5ee24bf4ece58ab99b16fbb465ce6dc0/pytz-2018.7-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 3.4MB/s 
Collecting python-dateutil>=2.5.0 (from pandas>=0.14->dclab==0.8.0)
  Downloading https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl (225kB)
    100% |████████████████████████████████| 235kB 1.5MB/s 
Installing collected packages: numpy, fcswrite, six, h5py, pillow, enum34, futures, imageio, nptdms, pathlib, scipy, pytz, python-dateutil, pandas, patsy, statsmodels, dclab
  Running setup.py install for imageio ... done
  Running setup.py install for pathlib ... done
  Running setup.py install for dclab ... done
Successfully installed dclab-0.8.0 enum34-1.1.6 fcswrite-0.4.1 futures-3.2.0 h5py-2.8.0 imageio-2.4.1 nptdms-0.13.0 numpy-1.15.4 pandas-0.23.4 pathlib-1.0.1 patsy-0.5.1 pillow-5.3.0 python-dateutil-2.7.5 pytz-2018.7 scipy-1.1.0 six-1.11.0 statsmodels-0.9.0
```

**Comment by grlee77** [comment]
> In pyFFTW, this is only the case when cython is available/importable: https://github.com/pyFFTW/pyFFTW/blob/master/setup.py#L755-L758

It is the opposite, though. Cython is added to setup_requires if it is not already available. I am not sure the reason that things were originally structured this way. 

> I am not sure whether we are talking about the same thing.

Indeed. I was thinking of the case where one is running `pip install .` from within the source directory checked out from GitHub, but you are talking about the user attempting to install from PyPI via pip.

Either way, it does not work for me if Cython is not already installed. When building from the source directory this is easily fixed by using requirements.txt:
`pip install -r requirements.txt .`

I am not yet sure why it does work for the example you provided, though.

**Comment by paulmueller** [comment]
> It is the opposite, though. Cython is added to setup_requires if it is not already available. I am not sure the reason that things were originally structured this way.

right, sorry about the confusion.

> I am not yet sure why it does work for the example you provided, though.

I can only wildly guess, maybe it is because you use Extension from ``distutils`` (https://github.com/pyFFTW/pyFFTW/blob/master/setup.py#L49)
and not from ``setuptools`` (https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/setup.py#L4)?

**Comment by TheNextLVL** [comment]
I'm building pyfftw in a arm64 platform(debian), and have the same issue. I'm installing with:

> apt install python3 python3-pip
> pip3 install pyfftw

The error that I get is:
```
Collecting pyFFTW
  Downloading https://files.pythonhosted.org/packages/fa/7f/e65fe8b9f1b66aab22c8d76c2f03180714a558fcef4a723263fa8f3754f8/pyFFTW-0.11.1.tar.gz (131kB)
    100% |################################| 133kB 1.0MB/s
Requirement already satisfied: CFFI>=1.0 in /usr/lib/python3/dist-packages (from sounddevice)
Requirement already satisfied: numpy<2.0,>=1.10 in /usr/lib/python3/dist-packages (from pyFFTW)
Building wheels for collected packages: paho-mqtt, pyFFTW
  Running setup.py bdist_wheel for paho-mqtt ... done
  Stored in directory: /root/.cache/pip/wheels/82/e5/de/d90d0f397648a1b58ffeea1b5742ac8c77f71fd43b550fa5a5
  Running setup.py bdist_wheel for pyFFTW ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ofpd2fp8/pyFFTW/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp8g28lcn8pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.5
  creating build/lib.linux-aarch64-3.5/pyfftw
  copying pyfftw/config.py -> build/lib.linux-aarch64-3.5/pyfftw
  copying pyfftw/_version.py -> build/lib.linux-aarch64-3.5/pyfftw
  copying pyfftw/__init__.py -> build/lib.linux-aarch64-3.5/pyfftw
  creating build/lib.linux-aarch64-3.5/pyfftw/builders
  copying pyfftw/builders/builders.py -> build/lib.linux-aarch64-3.5/pyfftw/builders
  copying pyfftw/builders/_utils.py -> build/lib.linux-aarch64-3.5/pyfftw/builders
  copying pyfftw/builders/__init__.py -> build/lib.linux-aarch64-3.5/pyfftw/builders
  creating build/lib.linux-aarch64-3.5/pyfftw/interfaces
  copying pyfftw/interfaces/dask_fft.py -> build/lib.linux-aarch64-3.5/pyfftw/interfaces
  copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-aarch64-3.5/pyfftw/interfaces
  copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-aarch64-3.5/pyfftw/interfaces
  copying pyfftw/interfaces/_utils.py -> build/lib.linux-aarch64-3.5/pyfftw/interfaces
  copying pyfftw/interfaces/cache.py -> build/lib.linux-aarch64-3.5/pyfftw/interfaces
  copying pyfftw/interfaces/__init__.py -> build/lib.linux-aarch64-3.5/pyfftw/interfaces
  UPDATING build/lib.linux-aarch64-3.5/pyfftw/_version.py
  set build/lib.linux-aarch64-3.5/pyfftw/_version.py to '0.11.1'
  running build_ext
  Build pyFFTW with support for FFTW with
  double precision + openMP
  single precision + openMP
  long precision + openMP
  building 'pyfftw.pyfftw' extension
  error: unknown file type '.pyx' (from 'pyfftw/pyfftw.pyx')
```

**Comment by hgomersall** [comment]
Ooooo ARM! This is _completely_ untested, so fixes are much appreciated.

**Comment by hgomersall** [comment]
@TheNextLVL That was actually a separate issue. The Cython thing should still be fixed, but I have no idea if ARM works.

**Comment by TheNextLVL** [comment]
@hgomersall I posted here, because the old version 0.10.4 modifying the SOURCES.txt and changing the absolute paths to relative works great!
I'm using a debin aarm 64bits with the raspberry pi 3b.

**Comment by hgomersall** [comment]
@TheNextLVL but it's not working now properly?

**Comment by hgomersall** [comment]
That probably means we can pester the Debian maintainer to begin including it again!

**Comment by TheNextLVL** [comment]
hi @hgomersall , the version 0.10.4 works well in arm64 OS (aarch64). The new trough the error when install it trough pip.  I will update if I find a solution.

**Comment by f0k** [comment]
> but it's not working now properly?

Sorry for the pause. [My comment](https://github.com/pyFFTW/pyFFTW/issues/252#issuecomment-441103206) was also for a Raspberry Pi, I didn't think this was relevant. With my fix, it worked fine.

> I can only wildly guess, maybe it is because you use Extension from distutils (https://github.com/pyFFTW/pyFFTW/blob/master/setup.py#L49)

As I noted above, I could get rid of the problem by adding:
```
from Cython.Distutils import build_ext
```
to `setup.py`. @TheNextLVL: Can you try whether it's the same for you? Clone the source, add that line after the `try:`/`except ImportError:` imports, and try to install from the source directory with `pip install .`. If this compiles and installs fine and does not break compilation for anybody else (how can we be sure?), I'll happily send a PR.

**Comment by f0k** [comment]
> As I noted above, I could get rid of the problem by adding:
> 
> ```
> from Cython.Distutils import build_ext
> ```
> 
> to `setup.py`.

This is also one of the options endorsed in [Cython's documentation](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules):
> Another option is to make Cython a setup dependency of your system and use Cython’s build_ext module which runs cythonize as part of the build process:
>
> ```
> setup(
>     setup_requires=[
>         'cython>=0.x',
>     ],
>     extensions = [Extension("*", ["*.pyx"])],
>     cmdclass={'build_ext': Cython.Build.build_ext},
>     ...
> )

The other option is to wrap [the extensions list](https://github.com/pyFFTW/pyFFTW/blob/1d44777/setup.py#L562) in a `Cython.build.cythonize()` call.

Looking at the current `setup.py` of pyFFTW, I'm surprised that compilation works at all for some systems. What am I missing?

**Comment by grlee77** [comment]
I have reopened #226, which I think should resolve this issue for pip going forward. The presence of `pyproject.toml` causes pip to create an isolated build environment containing Cython, numpy, setuptool and wheel. I tested this when building locally from the source directory, but think it should also work from a PyPI source distribution whenever we make a new release containing this file.

**Comment by masip85** [comment]
I don't know if @TheNextLVL can bring us here some light, but with armv8 (aarch64) architecture, and a compiled FFTW with:
./configure --enable-single --enable-neon ARM_CPU_TYPE=cortex-a8

I get:
```

Collecting pyfftw
  Downloading pyFFTW-0.12.0.tar.gz (137 kB)
Requirement already satisfied: numpy<2.0,>=1.10 in /opt/conda/lib/python3.7/site-packages (from pyfftw) (1.18.5)
Building wheels for collected packages: pyfftw
  Building wheel for pyfftw (setup.py): started
  Building wheel for pyfftw (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ipy13hgq/pyfftw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ipy13hgq/pyfftw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7s67sr84
       cwd: /tmp/pip-install-ipy13hgq/pyfftw/
  Complete output (55 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.7
  creating build/lib.linux-aarch64-3.7/pyfftw
  copying pyfftw/config.py -> build/lib.linux-aarch64-3.7/pyfftw
  copying pyfftw/__init__.py -> build/lib.linux-aarch64-3.7/pyfftw
  copying pyfftw/_version.py -> build/lib.linux-aarch64-3.7/pyfftw
  creating build/lib.linux-aarch64-3.7/pyfftw/builders
  copying pyfftw/builders/builders.py -> build/lib.linux-aarch64-3.7/pyfftw/builders
  copying pyfftw/builders/_utils.py -> build/lib.linux-aarch64-3.7/pyfftw/builders
  copying pyfftw/builders/__init__.py -> build/lib.linux-aarch64-3.7/pyfftw/builders
  creating build/lib.linux-aarch64-3.7/pyfftw/interfaces
  copying pyfftw/interfaces/cache.py -> build/lib.linux-aarch64-3.7/pyfftw/interfaces
  copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-aarch64-3.7/pyfftw/interfaces
  copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-aarch64-3.7/pyfftw/interfaces
  copying pyfftw/interfaces/_utils.py -> build/lib.linux-aarch64-3.7/pyfftw/interfaces
  copying pyfftw/interfaces/__init__.py -> build/lib.linux-aarch64-3.7/pyfftw/interfaces
  copying pyfftw/interfaces/scipy_fft.py -> build/lib.linux-aarch64-3.7/pyfftw/interfaces
  copying pyfftw/interfaces/dask_fft.py -> build/lib.linux-aarch64-3.7/pyfftw/interfaces
  UPDATING build/lib.linux-aarch64-3.7/pyfftw/_version.py
  set build/lib.linux-aarch64-3.7/pyfftw/_version.py to '0.12.0'
  running build_ext
  Build pyFFTW with support for FFTW with
  single precision
  cythoning pyfftw/pyfftw.pyx to pyfftw/pyfftw.c
  /opt/conda/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-ipy13hgq/pyfftw/pyfftw/pyfftw.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)
  warning: pyfftw/pyfftw.pyx:344:22: Casting a GIL-requiring function into a nogil function circumvents GIL validation
  warning: pyfftw/pyfftw.pyx:364:23: Casting a GIL-requiring function into a nogil function circumvents GIL validation
  building 'pyfftw.pyfftw' extension
  creating build/temp.linux-aarch64-3.7
  creating build/temp.linux-aarch64-3.7/pyfftw
  gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python3.7m -I/tmp/pip-install-ipy13hgq/pyfftw/include -I/tmp/pip-install-ipy13hgq/pyfftw/pyfftw -I/opt/conda/lib/python3.7/site-packages/numpy/core/include -I/opt/conda/include -I/opt/conda/include/python3.7m -c pyfftw/pyfftw.c -o build/temp.linux-aarch64-3.7/pyfftw/pyfftw.o
  In file included from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                   from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from pyfftw/pyfftw.c:606:
  /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  pyfftw/pyfftw.c: In function ‘__pyx_f_6pyfftw_6pyfftw_byte_align.isra.64.constprop’:
  pyfftw/pyfftw.c:3969:6: warning: ‘__pyx_v_update_dtype’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (__pyx_t_1) {
        ^
  gcc -pthread -shared -B /opt/conda/compiler_compat -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-aarch64-3.7/pyfftw/pyfftw.o -L/opt/conda/lib -lfftw3f -lm -o build/lib.linux-aarch64-3.7/pyfftw/pyfftw.cpython-37m-aarch64-linux-gnu.so
  /opt/conda/compiler_compat/ld: /usr/local/lib/libfftw3f.a(tensor7.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `fftwf_dimcmp' which may bind externally can not be used when making a shared object; recompile with -fPIC
  /usr/local/lib/libfftw3f.a(tensor7.o): in function `fftwf_tensor_compress_contiguous.part.1':
  tensor7.c:(.text+0x374): dangerous relocation: unsupported relocation
  /opt/conda/compiler_compat/ld: /usr/local/lib/libfftw3f.a(tensor7.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `fftwf_dimcmp' which may bind externally can not be used when making a shared object; recompile with -fPIC
  /usr/local/lib/libfftw3f.a(tensor7.o): in function `fftwf_tensor_compress':
  tensor7.c:(.text+0x494): dangerous relocation: unsupported relocation
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyfftw
  Running setup.py clean for pyfftw
Failed to build pyfftw
Installing collected packages: pyfftw
    Running setup.py install for pyfftw: started
    Running setup.py install for pyfftw: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ipy13hgq/pyfftw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ipy13hgq/pyfftw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mx49h4hv/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.7m/pyfftw
         cwd: /tmp/pip-install-ipy13hgq/pyfftw/
    Complete output (33 lines):
    running install
    running build
    running build_py
    UPDATING build/lib.linux-aarch64-3.7/pyfftw/_version.py
    set build/lib.linux-aarch64-3.7/pyfftw/_version.py to '0.12.0'
    running build_ext
    Build pyFFTW with support for FFTW with
    single precision
    skipping 'pyfftw/pyfftw.c' Cython extension (up-to-date)
    building 'pyfftw.pyfftw' extension
    creating build/temp.linux-aarch64-3.7
    creating build/temp.linux-aarch64-3.7/pyfftw
    gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python3.7m -I/tmp/pip-install-ipy13hgq/pyfftw/include -I/tmp/pip-install-ipy13hgq/pyfftw/pyfftw -I/opt/conda/lib/python3.7/site-packages/numpy/core/include -I/opt/conda/include -I/opt/conda/include/python3.7m -c pyfftw/pyfftw.c -o build/temp.linux-aarch64-3.7/pyfftw/pyfftw.o
    In file included from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                     from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from pyfftw/pyfftw.c:606:
    /opt/conda/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    pyfftw/pyfftw.c: In function ‘__pyx_f_6pyfftw_6pyfftw_byte_align.isra.64.constprop’:
    pyfftw/pyfftw.c:3969:6: warning: ‘__pyx_v_update_dtype’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       if (__pyx_t_1) {
          ^
    gcc -pthread -shared -B /opt/conda/compiler_compat -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-aarch64-3.7/pyfftw/pyfftw.o -L/opt/conda/lib -lfftw3f -lm -o build/lib.linux-aarch64-3.7/pyfftw/pyfftw.cpython-37m-aarch64-linux-gnu.so
    /opt/conda/compiler_compat/ld: /usr/local/lib/libfftw3f.a(tensor7.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `fftwf_dimcmp' which may bind externally can not be used when making a shared object; recompile with -fPIC
    /usr/local/lib/libfftw3f.a(tensor7.o): in function `fftwf_tensor_compress_contiguous.part.1':
    tensor7.c:(.text+0x374): dangerous relocation: unsupported relocation
    /opt/conda/compiler_compat/ld: /usr/local/lib/libfftw3f.a(tensor7.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `fftwf_dimcmp' which may bind externally can not be used when making a shared object; recompile with -fPIC
    /usr/local/lib/libfftw3f.a(tensor7.o): in function `fftwf_tensor_compress':
    tensor7.c:(.text+0x494): dangerous relocation: unsupported relocation
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ipy13hgq/pyfftw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ipy13hgq/pyfftw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mx49h4hv/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.7m/pyfftw Check the logs for full command output.

```
To compile I installed:  gcc g++ in ubuntu bionic 64 bits

Is this the problem?
`": dangerous relocation: unsupported relocation"`

Is the same kind of problem when you say "that some architectures are not supported"? What I've seen is old comments saying arm is not tested, that still in that way?Some users seems to get it. What should I do? this?:

`python setup.py build_ext --inplace`

**Comment by hgomersall** [comment]
@masip85 try building FFTW with `--enable-shared` to turn on `-fPIC`. This is assumed for the Linux builds, which might be your issue.

**Comment by masip85** [comment]
@hgomersall it did! And I've able to make an import in a python rpi4. Last logs has been:

ubuntu@ubuntu:~/fftw/fftw-3.3.8$ **sudo make install**
```
[...]
make  install-am
make[2]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/api'
make[3]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/api'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 fftw3.h fftw3.f fftw3l.f03 fftw3q.f03 '/usr/local/include'
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 fftw3.f03 '/usr/local/include'
make[3]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/api'
make[2]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/api'
make[1]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/api'
Making install in libbench2
make[1]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/libbench2'
make[2]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/libbench2'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/libbench2'
make[1]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/libbench2'
Making install in .
make[1]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8'
make[2]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libfftw3f.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libfftw3f.so.3.5.8 /usr/local/lib/libfftw3f.so.3.5.8
libtool: install: (cd /usr/local/lib && { ln -s -f libfftw3f.so.3.5.8 libfftw3f.so.3 || { rm -f libfftw3f.so.3 && ln -s libfftw3f.so.3.5.8 libfftw3f.so.3; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libfftw3f.so.3.5.8 libfftw3f.so || { rm -f libfftw3f.so && ln -s libfftw3f.so.3.5.8 libfftw3f.so; }; })
libtool: install: /usr/bin/install -c .libs/libfftw3f.lai /usr/local/lib/libfftw3f.la
libtool: install: /usr/bin/install -c .libs/libfftw3f.a /usr/local/lib/libfftw3f.a
libtool: install: chmod 644 /usr/local/lib/libfftw3f.a
libtool: install: ranlib /usr/local/lib/libfftw3f.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/local/lib/cmake/fftw3'
 /usr/bin/install -c -m 644 FFTW3fConfig.cmake FFTW3fConfigVersion.cmake '/usr/local/lib/cmake/fftw3'
 /bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 fftw3f.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8'
make[1]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8'
Making install in threads
make[1]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/threads'
make[2]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/threads'
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/threads'
make[1]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/threads'
Making install in tests
make[1]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/tests'
make[2]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/tests'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/tests'
make[1]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/tests'
Making install in mpi
make[1]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/mpi'
make  install-am
make[2]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/mpi'
make[3]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/mpi'
make[3]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/mpi'
make[2]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/mpi'
make[1]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/mpi'
Making install in doc
make[1]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/doc'
Making install in FAQ
make[2]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/doc/FAQ'
make[3]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/doc/FAQ'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/doc/FAQ'
make[2]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/doc/FAQ'
make[2]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/doc'
make[3]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/doc'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/share/info'
 /usr/bin/install -c -m 644 ./fftw3.info ./fftw3.info-1 ./fftw3.info-2 '/usr/local/share/info'
 install-info --info-dir='/usr/local/share/info' '/usr/local/share/info/fftw3.info'
make[3]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/doc'
make[2]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/doc'
make[1]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/doc'
Making install in tools
make[1]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/tools'
make  install-am
make[2]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/tools'
make[3]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/tools'
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c fftwf-wisdom '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/fftwf-wisdom /usr/local/bin/fftwf-wisdom
 /bin/mkdir -p '/usr/local/bin'
 /usr/bin/install -c fftw-wisdom-to-conf '/usr/local/bin'
 /bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 fftw-wisdom-to-conf.1 fftwf-wisdom.1 '/usr/local/share/man/man1'
make[3]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/tools'
make[2]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/tools'
make[1]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/tools'
Making install in m4
make[1]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/m4'
make[2]: Entering directory '/home/ubuntu/fftw/fftw-3.3.8/m4'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/m4'
make[1]: Leaving directory '/home/ubuntu/fftw/fftw-3.3.8/m4'
```
ubuntu@ubuntu:~/fftw/fftw-3.3.8$ **pip3 install pyfftw**
```
Collecting pyfftw
  Using cached https://files.pythonhosted.org/packages/4b/38/6f9539d274d02fbc3262e2f9a0c9dbac9b53393b3ed935612993f8df54bf/pyFFTW-0.12.0.tar.gz
Collecting numpy<2.0,>=1.10 (from pyfftw)
  Downloading https://files.pythonhosted.org/packages/f1/2c/717bdd12404c73ec0c8c734c81a0bad7048866bc36a88a1b69fd52b01c07/numpy-1.19.0.zip (7.3MB)
    100% |████████████████████████████████| 7.3MB 76kB/s 
Building wheels for collected packages: pyfftw, numpy
  Running setup.py bdist_wheel for pyfftw ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/47/d0/c0/fc62cf84812a41ee84fdd2d6e6403a00a5423a8ff36dedfbfc
  Running setup.py bdist_wheel for numpy ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/ce/c2/bb/29b2edcc9ff7d32c3ec7e3431f5df9b28df4077f8b13bed9c1
Successfully built pyfftw numpy
Installing collected packages: numpy, pyfftw
Successfully installed numpy-1.19.0 pyfftw-0.12.0
```

 **But**, if a replicate the same in a docker container I get these errors:

> ImportError: libfftw3f.so.3: cannot open shared object file: No such file or directory

I am using docker-stacks project which alternates installation bewteen root and the user jovyan which is used to launch the container. If I do the make,and then and make install as root (for replicating behaviour above), You can see below install goes right. When I get the import error,I am using container as user ($NB_UID in Dockerfile).

------
```
Entering directory '/fftw/fftw-3.3.8/api'
make  install-am
make[2]: Entering directory '/fftw/fftw-3.3.8/api'
make[3]: Entering directory '/fftw/fftw-3.3.8/api'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 fftw3.h fftw3.f fftw3l.f03 fftw3q.f03 '/usr/local/include'
 /bin/mkdir -p '/usr/local/include'
 /usr/bin/install -c -m 644 fftw3.f03 '/usr/local/include'
make[3]: Leaving directory '/fftw/fftw-3.3.8/api'
make[2]: Leaving directory '/fftw/fftw-3.3.8/api'
make[1]: Leaving directory '/fftw/fftw-3.3.8/api'
Making install in libbench2
make[1]: Entering directory '/fftw/fftw-3.3.8/libbench2'
make[2]: Entering directory '/fftw/fftw-3.3.8/libbench2'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/fftw/fftw-3.3.8/libbench2'
make[1]: Leaving directory '/fftw/fftw-3.3.8/libbench2'
Making install in .
make[1]: Entering directory '/fftw/fftw-3.3.8'
make[2]: Entering directory '/fftw/fftw-3.3.8'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libfftw3f.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libfftw3f.so.3.5.8 /usr/local/lib/libfftw3f.so.3.5.8
libtool: install: (cd /usr/local/lib && { ln -s -f libfftw3f.so.3.5.8 libfftw3f.so.3 || { rm -f libfftw3f.so.3 && ln -s libfftw3f.so.3.5.8 libfftw3f.so.3; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libfftw3f.so.3.5.8 libfftw3f.so || { rm -f libfftw3f.so && ln -s libfftw3f.so.3.5.8 libfftw3f.so; }; })
libtool: install: /usr/bin/install -c .libs/libfftw3f.lai /usr/local/lib/libfftw3f.la
libtool: install: /usr/bin/install -c .libs/libfftw3f.a /usr/local/lib/libfftw3f.a
libtool: install: chmod 644 /usr/local/lib/libfftw3f.a
libtool: install: ranlib /usr/local/lib/libfftw3f.a
libtool: finish: PATH="/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/local/lib/cmake/fftw3'
 /usr/bin/install -c -m 644 FFTW3fConfig.cmake FFTW3fConfigVersion.cmake '/usr/local/lib/cmake/fftw3'
 /bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 fftw3f.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/fftw/fftw-3.3.8'
make[1]: Leaving directory '/fftw/fftw-3.3.8'
Making install in threads
make[1]: Entering directory '/fftw/fftw-3.3.8/threads'
make[2]: Entering directory '/fftw/fftw-3.3.8/threads'
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/fftw/fftw-3.3.8/threads'
make[1]: Leaving directory '/fftw/fftw-3.3.8/threads'
Making install in tests
make[1]: Entering directory '/fftw/fftw-3.3.8/tests'
make[2]: Entering directory '/fftw/fftw-3.3.8/tests'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/fftw/fftw-3.3.8/tests'
make[1]: Leaving directory '/fftw/fftw-3.3.8/tests'
Making install in mpi
make[1]: Entering directory '/fftw/fftw-3.3.8/mpi'
make  install-am
make[2]: Entering directory '/fftw/fftw-3.3.8/mpi'
make[3]: Entering directory '/fftw/fftw-3.3.8/mpi'
make[3]: Leaving directory '/fftw/fftw-3.3.8/mpi'
make[2]: Leaving directory '/fftw/fftw-3.3.8/mpi'
make[1]: Leaving directory '/fftw/fftw-3.3.8/mpi'
Making install in doc
make[1]: Entering directory '/fftw/fftw-3.3.8/doc'
Making install in FAQ
make[2]: Entering directory '/fftw/fftw-3.3.8/doc/FAQ'
make[3]: Entering directory '/fftw/fftw-3.3.8/doc/FAQ'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/fftw/fftw-3.3.8/doc/FAQ'
make[2]: Leaving directory '/fftw/fftw-3.3.8/doc/FAQ'
make[2]: Entering directory '/fftw/fftw-3.3.8/doc'
make[3]: Entering directory '/fftw/fftw-3.3.8/doc'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/share/info'
 /usr/bin/install -c -m 644 ./fftw3.info ./fftw3.info-1 ./fftw3.info-2 '/usr/local/share/info'
 install-info --info-dir='/usr/local/share/info' '/usr/local/share/info/fftw3.info'
make[3]: Leaving directory '/fftw/fftw-3.3.8/doc'
make[2]: Leaving directory '/fftw/fftw-3.3.8/doc'
make[1]: Leaving directory '/fftw/fftw-3.3.8/doc'
Making install in tools
make[1]: Entering directory '/fftw/fftw-3.3.8/tools'
make  install-am
make[2]: Entering directory '/fftw/fftw-3.3.8/tools'
make[3]: Entering directory '/fftw/fftw-3.3.8/tools'
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c fftwf-wisdom '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/fftwf-wisdom /usr/local/bin/fftwf-wisdom
 /bin/mkdir -p '/usr/local/bin'
 /usr/bin/install -c fftw-wisdom-to-conf '/usr/local/bin'
 /bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 fftw-wisdom-to-conf.1 fftwf-wisdom.1 '/usr/local/share/man/man1'
make[3]: Leaving directory '/fftw/fftw-3.3.8/tools'
make[2]: Leaving directory '/fftw/fftw-3.3.8/tools'
make[1]: Leaving directory '/fftw/fftw-3.3.8/tools'
Making install in m4
make[1]: Entering directory '/fftw/fftw-3.3.8/m4'
make[2]: Entering directory '/fftw/fftw-3.3.8/m4'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/fftw/fftw-3.3.8/m4'
make[1]: Leaving directory '/fftw/fftw-3.3.8/m4'
Removing intermediate container 85fc4cb40a72
 ---> 2f05fa5792ea
```
```
Step 11/12 : USER $NB_UID
 ---> Running in b7ad6f557aeb
Removing intermediate container b7ad6f557aeb
 ---> c2d3d148b919
```
```
Step 12/12 : RUN pip install pyfftw &&  rm -rf /home/$NB_USER/.local &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER
 ---> Running in bfe113fcee5e
Collecting pyfftw
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0xffff98b37750>: Failed to establish a new connection: [Errno -2] Name or service not known')': /packages/4b/38/6f9539d274d02fbc3262e2f9a0c9dbac9b53393b3ed935612993f8df54bf/pyFFTW-0.12.0.tar.gz
  Downloading pyFFTW-0.12.0.tar.gz (137 kB)
Requirement already satisfied: numpy<2.0,>=1.10 in /opt/conda/lib/python3.7/site-packages (from pyfftw) (1.18.5)
Building wheels for collected packages: pyfftw
  Building wheel for pyfftw (setup.py): started
  Building wheel for pyfftw (setup.py): finished with status 'done'
  Created wheel for pyfftw: filename=pyFFTW-0.12.0-cp37-cp37m-linux_aarch64.whl size=352636 sha256=6b70c289fe0a10c3ff79a46322393f67bdbe55a17d16f728e73bae0345d2ca8b
  Stored in directory: /home/jovyan/.cache/pip/wheels/e7/8f/46/c251fd0155e6f2af332f77097a98ecb5c8eb8811b3c935ec91
Successfully built pyfftw
Installing collected packages: pyfftw
Successfully installed pyfftw-0.12.0
Removing intermediate container bfe113fcee5e
 ---> e05cc95ec522
Successfully built e05cc95ec522
```

As you can see same .so libraries are installed. My question is, is in this case pyfftw looking for a wrong .so reference?

**Comment by hgomersall** [comment]
Is `/usr/lib/local` perhaps not in the ld search path in the docker container? It often isn't by default. You can see using [this incantation](https://stackoverflow.com/a/21610523/709852).

**Comment by masip85** [comment]
In fact, it is:
SEARCH_DIR("=/usr/local/lib/aarch64-linux-gnu"); SEARCH_DIR("=/lib/aarch64-linux-gnu"); SEARCH_DIR("=/usr/lib/aarch64-linux-gnu"); SEARCH_DIR("=/usr/local/lib"); SEARCH_DIR("=/lib"); SEARCH_DIR("=/usr/lib"); SEARCH_DIR("=/usr/aarch64-linux-gnu/lib");

**Comment by hgomersall** [comment]
@masip85 Oh, in that case I don't know :(

**Comment by masip85** [comment]
I think is related to python version and this linking operation?:
```
libtool: install: (cd /usr/local/lib && { ln -s -f libfftw3f.so.3.5.8 libfftw3f.so.3 || { rm -f libfftw3f.so.3 && ln -s libfftw3f.so.3.5.8 libfftw3f.so.3; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libfftw3f.so.3.5.8 libfftw3f.so || { rm -f libfftw3f.so && ln -s libfftw3f.so.3.5.8 libfftw3f.so; }; })
```

**Comment by hgomersall** [comment]
What does `ldd` on the python `.so` module show?

**Comment by masip85** [comment]
Ok, my mistake with ldconfig is that I thought it listed the links. It seems that ldconfig not only list the shared object links, in fact, it initialize (and as command supply an alternative to LD_LIBRARY_PATH configuration). After initializing it, pyfftw import reads fine shared library. Now I am going to test armv8 neon compiled fftw in a rpi4 :)

Therefore, this is the end of the Dockerfile:

USER root
RUN apt-get update
RUN apt-get install -yq --no-install-recommends \
	 htop 
RUN apt-get install -y gcc g++ 
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN /bin/bash -c ' \
    cd / && mkdir fftw && cd /fftw; \ 
    wget http://www.fftw.org/fftw-3.3.8.tar.gz; \
    tar -zxvf fftw-3.3.8.tar.gz; \
    cd /fftw/fftw-3.3.8; \
    ./configure --enable-single --enable-shared --enable-neon ARM_CPU_TYPE=cortex-a8 ; \
    make ; \
    make install ; \
    '
USER $NB_UID

RUN pip install pyfftw && \
	rm -rf /home/$NB_USER/.local && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

USER root
RUN ldconfig -v
USER $NB_UID

**Comment by hgomersall** [comment]
So it's working now?

**Comment by masip85** [comment]
> So it's working now?

The import does,so installing is perfect.

**Comment by hgomersall** [comment]
@masip85 this is actually quite a big deal. I'd be interested in knowing more when you've had a chance to work through it on ARM. It sounds like you have two platforms - a Cortex-A8 and an Pi4 Cortex-A72? I suggest gathering discussion for this on #144

**Comment by reinderien** [comment]
Got bit by this on a bare Python 3.9 virtualenv; I had to `pip install`

- `setuptools`
- `wheel`
- `Cython`

for it to work.

**Comment by congzhangzh** [comment]
after install cython, it begin to work.

Why not mark cython as dependence, and then pip do it automate for us?

**Comment by paulmueller** [comment]
This should be fixed by #226

**Comment by phara92** [comment]
PyPI is not updated yet, so building the docker file: 
```
FROM debian:testing-slim
RUN apt-get update && \
    apt-get install -qq libfftw3-dev python3-pip && \
    pip install pyfftw
```
still fails with
```
  Building wheel for pyfftw (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t86krbgp/pyfftw_4b764303802f4cdcabe280f3715db9b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t86krbgp/pyfftw_4b764303802f4cdcabe280f3715db9b1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ackyrf8v
       cwd: /tmp/pip-install-t86krbgp/pyfftw_4b764303802f4cdcabe280f3715db9b1/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/pyfftw
  copying pyfftw/config.py -> build/lib.linux-x86_64-3.9/pyfftw
  copying pyfftw/_version.py -> build/lib.linux-x86_64-3.9/pyfftw
  copying pyfftw/__init__.py -> build/lib.linux-x86_64-3.9/pyfftw
  creating build/lib.linux-x86_64-3.9/pyfftw/builders
  copying pyfftw/builders/_utils.py -> build/lib.linux-x86_64-3.9/pyfftw/builders
  copying pyfftw/builders/builders.py -> build/lib.linux-x86_64-3.9/pyfftw/builders
  copying pyfftw/builders/__init__.py -> build/lib.linux-x86_64-3.9/pyfftw/builders
  creating build/lib.linux-x86_64-3.9/pyfftw/interfaces
  copying pyfftw/interfaces/scipy_fft.py -> build/lib.linux-x86_64-3.9/pyfftw/interfaces
  copying pyfftw/interfaces/_utils.py -> build/lib.linux-x86_64-3.9/pyfftw/interfaces
  copying pyfftw/interfaces/dask_fft.py -> build/lib.linux-x86_64-3.9/pyfftw/interfaces
  copying pyfftw/interfaces/numpy_fft.py -> build/lib.linux-x86_64-3.9/pyfftw/interfaces
  copying pyfftw/interfaces/__init__.py -> build/lib.linux-x86_64-3.9/pyfftw/interfaces
  copying pyfftw/interfaces/scipy_fftpack.py -> build/lib.linux-x86_64-3.9/pyfftw/interfaces
  copying pyfftw/interfaces/cache.py -> build/lib.linux-x86_64-3.9/pyfftw/interfaces
  UPDATING build/lib.linux-x86_64-3.9/pyfftw/_version.py
  set build/lib.linux-x86_64-3.9/pyfftw/_version.py to '0.12.0'
  running build_ext
  Build pyFFTW with support for FFTW with
  double precision + openMP
  single precision + openMP
  long precision + openMP
  building 'pyfftw.pyfftw' extension
  error: unknown file type '.pyx' (from 'pyfftw/pyfftw.pyx')
  ----------------------------------------
  ERROR: Failed building wheel for pyfftw
  Running setup.py clean for pyfftw
Failed to build pyfftw
Installing collected packages: numpy, pyfftw
    Running setup.py install for pyfftw: started
    Running setup.py install for pyfftw: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t86krbgp/pyfftw_4b764303802f4cdcabe280f3715db9b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t86krbgp/pyfftw_4b764303802f4cdcabe280f3715db9b1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rho6revo/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/pyfftw
         cwd: /tmp/pip-install-t86krbgp/pyfftw_4b764303802f4cdcabe280f3715db9b1/
    Complete output (12 lines):
    running install
    running build
    running build_py
    UPDATING build/lib.linux-x86_64-3.9/pyfftw/_version.py
    set build/lib.linux-x86_64-3.9/pyfftw/_version.py to '0.12.0'
    running build_ext
    Build pyFFTW with support for FFTW with
    double precision + openMP
    single precision + openMP
    long precision + openMP
    building 'pyfftw.pyfftw' extension
    error: unknown file type '.pyx' (from 'pyfftw/pyfftw.pyx')
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t86krbgp/pyfftw_4b764303802f4cdcabe280f3715db9b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t86krbgp/pyfftw_4b764303802f4cdcabe280f3715db9b1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rho6revo/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/pyfftw Check the logs for full command output.
```

Building directly from the github repo works:
```
FROM debian:testing-slim
RUN apt-get update && apt-get install -qq libfftw3-dev python3-pip git
RUN pip install git+https://github.com/pyFFTW/pyFFTW
```

**Comment by grlee77** [comment]
should be fixed by presence of pyproject.toml in v0.13.0

**Comment by phiadaarr** [comment]
> should be fixed by presence of pyproject.toml in v0.13.0

Works for me. Thanks!
