### ISSUE TITLE
Clean install from requirements.txt file - ImportError: No module named 'numpy'

### ISSUE THREAD

**Issue by ferdinandvanwyk** [pyFFTW/pyFFTW#64]
I am trying to set up a project using pyFFTW and want all my requirements to be listed in the `requirements.txt` file and installed via

```
pip install -r requirements.txt
```

However, given a `requirements.txt` file with only the following inside

```
numpy
pyfftw
```

When I run the installation command, I get the following error:

```
$ pip install -r requirements.txt 
Downloading/unpacking numpy (from -r requirements.txt (line 1))
  Downloading numpy-1.9.2.tar.gz (4.0MB): 4.0MB downloaded
  Running setup.py (path:/home/vanwyk/py_envs/py3/build/numpy/setup.py) egg_info for package numpy
    Running from numpy source directory.

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking pyfftw (from -r requirements.txt (line 2))
  Downloading pyFFTW-0.9.2.tar.gz (336kB): 336kB downloaded
  Running setup.py (path:/home/vanwyk/py_envs/py3/build/pyfftw/setup.py) egg_info for package pyfftw
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/vanwyk/py_envs/py3/build/pyfftw/setup.py", line 25, in <module>
        import numpy
    ImportError: No module named 'numpy'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/vanwyk/py_envs/py3/build/pyfftw/setup.py", line 25, in <module>

    import numpy

ImportError: No module named 'numpy'

----------------------------------------
Cleaning up...
```

But if I install `numpy` and `pyfftw` separately things work fine. Is there any way to make installing from  `requirements.txt` work so installing dependencies doesn't become a two-step process?

Ubuntu 14.04 LTS
Python 3.4 running in virtualenv

**Comment by hgomersall** [comment]
Hmmm, this is a good question. It _should_ use the requirements.txt from pyfftw, which stipulates numpy, but it doesn't seem to be (clearly). What happens if you just pip install numpy?

**Comment by hgomersall** [comment]
Sorry s/pip install numpy/pip install pyfftw

**Comment by ferdinandvwyk** [comment]
Running `pip install numpy` and then `pip install pyfftw` works fine.

**Comment by hgomersall** [comment]
No, I mean, just running `pip install pyfftw` without numpy first.

**Comment by ferdinandvwyk** [comment]
I get the following:
```
$ pip list
pip (1.5.6)
setuptools (3.6)

$ pip install pyfftw
Downloading/unpacking pyfftw
  Downloading pyFFTW-0.9.2.tar.gz (336kB): 336kB downloaded
  Running setup.py (path:/home/vanwyk/py_envs/test/build/pyfftw/setup.py) egg_info for package pyfftw
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/vanwyk/py_envs/test/build/pyfftw/setup.py", line 25, in <module>
        import numpy
    ImportError: No module named 'numpy'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/vanwyk/py_envs/test/build/pyfftw/setup.py", line 25, in <module>

    import numpy

ImportError: No module named 'numpy'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/vanwyk/py_envs/test/build/pyfftw
Storing debug log for failure

 in /home/vanwyk/.pip/pip.log
```

The `pip.log` file contains the following:
```
------------------------------------------------------------
/home/vanwyk/py_envs/test/bin/pip run on Sun Jul 19 13:22:59 2015
Downloading/unpacking pyfftw
  Getting page https://pypi.python.org/simple/pyfftw/
  URLs to search for versions for pyfftw:
  * https://pypi.python.org/simple/pyfftw/
  Analyzing links from page https://pypi.python.org/simple/pyfftw/
    Skipping link https://pypi.python.org/packages/2.7/p/pyFFTW/pyFFTW-0.6.1.win32-py2.7.msi#md5=8132b43ebe57dd294e2355532856189c (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/2.7/p/pyFFTW/pyFFTW-0.7.0.win32-py2.7.msi#md5=1840336903a7d310a23680a4d7388461 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/2.7/p/pyFFTW/pyFFTW-0.8.0.win32-py2.7.msi#md5=e07d5facb231d8fc2829d353edcfe144 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/2.7/p/pyFFTW/pyFFTW-0.8.1.win32-py2.7.msi#md5=521a2ece327d95338b982ecbc0a798ac (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/2.7/p/pyFFTW/pyFFTW-0.8.2.win32-py2.7.msi#md5=bbd7ce20f6c2154a051e2961fdf4a78d (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/2.7/p/pyFFTW/pyFFTW-0.9.0.win32-py2.7.msi#md5=cb35ac252902b15c5e40c8fdc8008631 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/2.7/p/pyFFTW/pyFFTW-0.9.1.win32-py2.7.msi#md5=3e1569a17eda24932c3abf24e5d8f718 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/2.7/p/pyFFTW/pyFFTW-0.9.2.win-amd64-py2.7.exe#md5=07ed0ec52f075101d865a60fa4d4b834 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/2.7/p/pyFFTW/pyFFTW-0.9.2.win32-py2.7.exe#md5=34139d46ab9d45ab1ecb2e4e3e68abb7 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.2/p/pyFFTW/pyFFTW-0.9.0.win32-py3.2.msi#md5=cdca12478abe7d43ca13c34686f6bcee (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/3.2/p/pyFFTW/pyFFTW-0.9.2.win-amd64-py3.2.exe#md5=2063d35a39bd7530cb76949d580c5f98 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.2/p/pyFFTW/pyFFTW-0.9.2.win32-py3.2.exe#md5=3a4240258e77b146078b6e2cbe7c98de (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.3/p/pyFFTW/pyFFTW-0.9.0.win32-py3.3.msi#md5=07f81256baea520cb7a42ed67cae2105 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/3.3/p/pyFFTW/pyFFTW-0.9.1.win32-py3.3.msi#md5=4011f4d981b931fea6d05d72f4a47da9 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .msi
    Skipping link https://pypi.python.org/packages/3.3/p/pyFFTW/pyFFTW-0.9.2.win-amd64-py3.3.exe#md5=01f8aef7d5afa377186233e6a2cade00 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/3.3/p/pyFFTW/pyFFTW-0.9.2.win32-py3.3.exe#md5=275f24a57bed5ecfa39b211d910b2dd0 (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .exe
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.5.0.tar.gz#md5=3e53d9e1db5dd34ecb447016374668c2 (from https://pypi.python.org/simple/pyfftw/), version: 0.5.0
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.5.1.tar.gz#md5=4fac5148affd92cc8355ec3230710562 (from https://pypi.python.org/simple/pyfftw/), version: 0.5.1
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.6.0.tar.gz#md5=f1e228ad5666766f30de64d845031a8f (from https://pypi.python.org/simple/pyfftw/), version: 0.6.0
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.6.1.tar.gz#md5=4f3dc159e2101c08e2cd16bcfd0cb1c8 (from https://pypi.python.org/simple/pyfftw/), version: 0.6.1
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.7.0.tar.gz#md5=538117261f735e42265575173d27eaee (from https://pypi.python.org/simple/pyfftw/), version: 0.7.0
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.8.0.tar.gz#md5=9162d59f048d277f05967ad342743229 (from https://pypi.python.org/simple/pyfftw/), version: 0.8.0
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.8.1.tar.gz#md5=b7673125e89d73612944c08d32d9489d (from https://pypi.python.org/simple/pyfftw/), version: 0.8.1
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.8.2.tar.gz#md5=d5e55665688a4b51f0b65d9508fe8f3d (from https://pypi.python.org/simple/pyfftw/), version: 0.8.2
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.9.0.tar.gz#md5=e8dc47edcf9a82efa4d02347c3801058 (from https://pypi.python.org/simple/pyfftw/), version: 0.9.0
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.9.1.tar.gz#md5=a370f15f2c8caa509511cb39087b2b0c (from https://pypi.python.org/simple/pyfftw/), version: 0.9.1
    Found link https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.9.2.tar.gz#md5=34fcbc68afb8ebe5f040a02a8d20d565 (from https://pypi.python.org/simple/pyfftw/), version: 0.9.2
    Skipping link http://hgomersall.github.com/pyFFTW/ (from https://pypi.python.org/simple/pyfftw/); not a file
    Skipping link http://www.fftw.org/ (from https://pypi.python.org/simple/pyfftw/); not a file
    Skipping link http://www.fftw.org/install/windows.html (from https://pypi.python.org/simple/pyfftw/); unknown archive format: .html
    Skipping link https://github.com/hgomersall/pyFFTW (from https://pypi.python.org/simple/pyfftw/); not a file
  Using version 0.9.2 (newest of versions: 0.9.2, 0.9.1, 0.9.0, 0.8.2, 0.8.1, 0.8.0, 0.7.0, 0.6.1, 0.6.0, 0.5.1, 0.5.0)
  Downloading from URL https://pypi.python.org/packages/source/p/pyFFTW/pyFFTW-0.9.2.tar.gz#md5=34fcbc68afb8ebe5f040a02a8d20d565 (from https://pypi.python.org/simple/pyfftw/)
  Running setup.py (path:/home/vanwyk/py_envs/test/build/pyfftw/setup.py) egg_info for package pyfftw
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/vanwyk/py_envs/test/build/pyfftw/setup.py", line 25, in <module>
        import numpy
    ImportError: No module named 'numpy'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/vanwyk/py_envs/test/build/pyfftw/setup.py", line 25, in <module>

    import numpy

ImportError: No module named 'numpy'

----------------------------------------
Cleaning up...
  Removing temporary dir /home/vanwyk/py_envs/test/build...
Command python setup.py egg_info failed with error code 1 in /home/vanwyk/py_envs/test/build/pyfftw
Exception information:
Traceback (most recent call last):
  File "/home/vanwyk/py_envs/test/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/vanwyk/py_envs/test/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/vanwyk/py_envs/test/lib/python3.4/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/home/vanwyk/py_envs/test/lib/python3.4/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/vanwyk/py_envs/test/lib/python3.4/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /home/vanwyk/py_envs/test/build/pyfftw
```

**Comment by hgomersall** [comment]
Ok, this is probably related to #46. The setup.py stuff needs a bit of attention it seems. Is this a big deal for you in the meantime?

**Comment by ferdinandvwyk** [comment]
Thanks, no it's not a dealbreaker since I'm not really a pro developer. I don't know how to release packages etc. but here's a random example of how another project manages package dependencies (including numpy). Maybe it'll be useful to you: https://github.com/mwaskom/seaborn/blob/master/setup.py

Thanks for looking into it!

**Comment by hgomersall** [comment]
Is this fixed with https://github.com/hgomersall/pyFFTW/commit/208cb158c4e5cd0a2e2ee2be3ea55eb224220de3?

**Comment by ferdinandvwyk** [comment]
Not that I can see, I still get the same errors as above. As the errors show, the problem is occurring here in the `setup.py`:

```python
def get_include_dirs():                                                         
    import numpy                                                                
    from pkg_resources import get_build_platform                                
                                                                                
    include_dirs = [os.path.join(os.getcwd(), 'include'),                       
                    os.path.join(os.getcwd(), 'pyfftw'),                        
                    numpy.get_include()]                                        
                                                                                
    if get_build_platform() in ('win32', 'win-amd64'):                          
        include_dirs.append(os.path.join(os.getcwd(), 'include', 'win'))        
                                                                                
    return include_dirs
```

This `numpy import` is being called before `setup(**setup_args)` is called which would install numpy since you've specified `*_requires = ['numpy>=1.6',]`. However, I don't understand the whole structure of the `setup.py`, so maybe it's obvious why you're doing this.

**Comment by hgomersall** [comment]
Is it still trying to grab the package from pypi? If not, I don't really know how to fix it. I'll ask a question on SO if not.

If it is, you could try creating a wheel of both numpy and the latest version of pyfftw and then install from that (with --find-links= and --no-index args to pip to prevent it from using pypi).

**Comment by ferdinandvwyk** [comment]
Yes, it's still trying to grab the package from pypi.

Do I host those wheels in my own package?

**Comment by hgomersall** [comment]
Essentially yes. Take a look at the wheel documentation. You'll build the wheel and then install from that built wheel rather than using pypi.

**Comment by sjpet** [comment]
Did the wheel solution work? I just ran into the same problem trying to test a pyfftw-dependent project with tox.

**Comment by hgomersall** [comment]
I think it's as fixed as it can be for the time being: https://github.com/pypa/pip/issues/2381

Apologies, I can't think of what else to do.

**Comment by hgomersall** [comment]
Actually, it _might_ work when the pypi release is made. It should happen soon - I'm just clearing up some annoyances with windows.

**Comment by ferdinandvwyk** [comment]
Thanks, just post back here hgomersall and I'll test it again. sjpet, I haven't implemented a wheel solution since it's not mission critical for me but can't see any reason it wouldn't work.

**Comment by jakirkham** [comment]
This is solved in `master` and will be available in the next release. Have also tested this locally. Thanks everyone.
